version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth:
    build: ..
    container_name: auth_service
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  db_data:
